fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "no-reply@joeymasip.com"
    sender_name: "Symfony 4 Rest API with JWT"
  registration:
    #        form:
    #            type: AppBundle\Form\UserRegisterType
    confirmation:
      enabled: true
      template:   FOSUserBundle:Registration:email.txt.twig
      from_email:
        address:        "no-reply@joeymasip.com"
        sender_name:    "No Reply Registration"
  resetting:
    email:
      template:   FOSUserBundle:Resetting:email.txt.twig